### ISSUE TITLE
Alex c’est quoi cette merde

### ISSUE THREAD

**Issue by mathishp33** [Alexandre1a/App_Repo#11]
Alex arrête ça tt suite même le prof de NSI fait mieux faut que tu review ton code plus souvent

**Comment by dgdzd** [comment]
J'ai un bon tutoriel pour toi : 

[clique](https://youtu.be/dQw4w9WgXcQ?si=wGYcSBxYvAGkpbfO)

**Comment by mathishp33** [comment]
Pas mal c’est un bon tuto, le mec explique bien

**Comment by Alexandre1a** [comment]
Bah c'est un launcher simple avec un frontend simple et un backend de MAJ en développement
